"""Segunda  migração

Revision ID: 0ade22958c64
Revises: acbfb66841f5
Create Date: 2023-03-12 13:25:57.642414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ade22958c64'
down_revision = 'acbfb66841f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_parceiro',
    sa.Column('id_parceiro', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('status_aprovacao', sa.String(length=10), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id_pessoa'], ),
    sa.PrimaryKeyConstraint('id_parceiro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_parceiro')
    # ### end Alembic commands ###
